### ISSUE TITLE
protocol path STREAM_PROTOCOL_PATH  in generic ioc is not set, the proto is found in /epics/support/configure/protocol/ 

### ISSUE THREAD

**Issue by amichelotti** [infn-epics/infn-epics-ioc#3]
I added SMC support https://github.com/infn-epics/infn-epics-ioc/blob/47d13dba5036992482f8f778fba15600de483fe3/Dockerfile#L136 
I also used ansible to install it, in particular I added the protocol file:

https://github.com/infn-epics/ibek-support-infn/blob/2cba4c287b76f8b2dd4e4972bdf4c22fe9e5d799/smc/smc.install.yml#L20-L21

The protocol file is correctly picked by ansible. This protocol file is found in /epics/support/configure/protocol/ .

When I run the ioc through:
```yaml
oc_name: chiller-chlboc02
description:  CHILLER  TEMPLATE
entities:
- type: smc.CreateCtrl
  name: "CHILLER01"
  IP: 192.168.197.80
  TCPPORT: 4001
  P: SPARC:CHL:SMC:CHLBOC02
  DEV_ID: 01
- type: epics.PostStartupCommand 
  command: |
          dbl
          dbl("*") > /nfs/config/chiller-chlboc02/pvlist.txt           ## dumps PV NAMES
```

It would be nice if the variable could be automatically set to /epics/support/configure/ without specify it in the yaml.

**Comment by gilesknap** [comment]
I believe the ansible role copies the protocol files to /epics/runtime/protocol - with the intention that only one path is required in STREAM_PROTOCOL_PATH. It is something that needs to be supplied in the yaml but I agree that we could automatically add that if StreamDevice is included. Will take a look at this on my return next week.

It is important to note that the old way of doing PROTOCOL PATH is not compatible with this approach (we used to append to PROTOCOL_PATH in the support yaml and give the full path to the support module), but I would like to adopt the ansible support role as the only approach.

The main reason for adopting the new approach is for RTEMS and other embedded IOCs which may not have access to the full /epics/ tree at runtime. But for consistency I have used this for linux IOCs too, that way all files needed at runtime are found in /epics/runtime and /epics/ioc and PROTOCOL_PATH management is simplified.

**Comment by gilesknap** [comment]
My apologies for not remembering to discuss this change with you when updating this project.

My above comment is not quite correct. The protocol files are collected  in `/epics/support/configure/protocol` by the Ansible support role as you stated. But that folder is moved to `/epics/runtime/protocol` at runtime.

This is only done for consistency with embedded IOCs and is performed here: https://github.com/infn-epics/infn-epics-ioc/blob/f8e72d8bb3ff4e7c1a280ba636502f6b51b3da6c/ioc/start.sh#L136-L139 
You could choose to remove those lines from your own start.sh - but you might as well stick with the standard. I like that all files required at runtime (other than shared libraries for Linux IOCs) are all in one folder.

The short answer is that all my DLS IOC instances' YAML start with the same lines below, I manually add them and we don't have a tidy way of automating that at present. (Having these lines and no StreamDevice is benign). 

```yaml
# yaml-language-server: $schema=/epics/ibek-defs/ioc.schema.json

ioc_name: "{{  _global.get_env('IOC_NAME') }}"

description: VARIES BY IOC (but everything else is identical)

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TS_MIN_WEST
    value: "0"

  - type: epics.EpicsEnvSet
    name: STREAM_PROTOCOL_PATH
    value: /epics/runtime/protocol/

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"
```

It makes sense to put precisely these lines in `services-template-helm` file `/services/.ioc-template`. I'm not sure if that helps you as I don't know if you are using `services-template-helm`. If not, you could copy `https://github.com/epics-containers/services-template-helm/tree/main/template/services/.ioc_template` into your services project and use it as the starting point for all future IOC instance definitions.
